SELECT * FROM Products
--1. Create a cursor Product_Cursor to fetch all the rows from a products table.
DECLARE PRODUCT_CURSOR CURSOR FOR 
SELECT PRODUCT_ID,PRODUCT_NAME,PRICE FROM Products;

OPEN PRODUCT_CURSOR;

DECLARE @PRODUCT_ID INT,@PRODUCT_NAME VARCHAR(250),@PRICE DECIMAL(10,2);
FETCH NEXT FROM PRODUCT_CURSOR INTO @PRODUCT_ID,@PRODUCT_NAME,@PRICE;
WHILE @@FETCH_STATUS = 0
	BEGIN 
		PRINT 'PRODUCT_ID:'+CAST(@PRODUCT_ID AS VARCHAR)+
		' PRODUCT_NAME:'+@PRODUCT_NAME+' PRICE:'+CAST(@PRICE AS VARCHAR);

		FETCH NEXT FROM PRODUCT_CURSOR INTO @PRODUCT_ID,@PRODUCT_NAME,@PRICE;
	END;

CLOSE PRODUCT_CURSOR;
DEALLOCATE PRODUCT_CURSOR;

--Create a cursor Product_Cursor_Fetch to fetch the records in 
--form of ProductID_ProductName
DECLARE PRODUCT_CURSOR_FETCH CURSOR FOR 
SELECT PRODUCT_ID,PRODUCT_NAME FROM Products;

OPEN PRODUCT_CURSOR_FETCH;
DECLARE @PRODUCT_ID1 INT,@PRODUCT_NAME1 VARCHAR(250);
FETCH NEXT FROM PRODUCT_CURSOR_FETCH INTO @PRODUCT_ID1,@PRODUCT_NAME1;
WHILE @@FETCH_STATUS = 0
	BEGIN 
		PRINT CAST(@PRODUCT_ID1 AS VARCHAR)+'_'+@PRODUCT_NAME1;

		FETCH NEXT FROM PRODUCT_CURSOR_FETCH INTO @PRODUCT_ID1,@PRODUCT_NAME1;
	END;

CLOSE PRODUCT_CURSOR_FETCH;
DEALLOCATE PRODUCT_CURSOR_FETCH;

--Create a cursor Product_CursorDelete that deletes all the data from the Products table.
DECLARE PRODUCT_CURSOR_DELETE CURSOR FOR 
SELECT PRODUCT_ID FROM Products;

OPEN PRODUCT_CURSOR_DELETE;
DECLARE @PRODUCT_ID2 INT;
FETCH NEXT FROM PRODUCT_CURSOR_DELETE INTO @PRODUCT_ID2;
WHILE @@FETCH_STATUS = 0
	BEGIN 
		DELETE FROM Products WHERE Product_id=@PRODUCT_ID2
		PRINT 'PRODUCT ID :'+CAST(@PRODUCT_ID2 AS VARCHAR)+' DELETED.';

		FETCH NEXT FROM PRODUCT_CURSOR_DELETE INTO @PRODUCT_ID2;
	END;

CLOSE PRODUCT_CURSOR_DELETE;
DEALLOCATE PRODUCT_CURSOR_DELETE;
