CREATE TABLE STUDENT (ROLLNO INT, NAME VARCHAR(50), BIRTHDATE DATE, SPI DECIMAL(4,2), CITY VARCHAR(50), BACKLOG INT,BRANCH VARCHAR(50))

SELECT * FROM STUDENT

INSERT INTO STUDENT VALUES(101,'KEYUR','1992-01-05',8.5,'RAJKOT',2,'CE')