CREATE TABLE Person (
    PersonID INT PRIMARY KEY,
    PersonName VARCHAR(100) NOT NULL,
    Salary DECIMAL(8, 2) NOT NULL,
    JoiningDate DATETIME NOT NULL,
    City VARCHAR(100) NOT NULL,
    Age INT NULL,
    BirthDate DATETIME NOT NULL
);

CREATE TABLE PersonLog (
    PLogID INT PRIMARY KEY IDENTITY(1,1),
    PersonID INT NOT NULL,
    PersonName VARCHAR(250) NOT NULL,
    Operation VARCHAR(50) NOT NULL,
    UpdateDate DATETIME NOT NULL,
    FOREIGN KEY (PersonID) REFERENCES Person(PersonID)
);
--1. Create a trigger that fires on INSERT, UPDATE and DELETE operation 
--on the Person table to display a message “Record is Affected.”
CREATE TRIGGER TR_PERSON_INS_UPD_DEL
ON PERSON
FOR INSERT, UPDATE, DELETE
AS
BEGIN
  PRINT 'RECORD AFFECTED.'
END;

SELECT * FROM Person
INSERT INTO Person VALUES (1, 'John Doe', 55000.00, '2024-01-15', 'New York', 30, '1994-05-22');
INSERT INTO Person VALUES (2, 'GHANSHYAM PANERA', 75000.00, '2024-01-16', 'LOS ANGLES', 19, '2006-09-19');


--2. Create a trigger that fires on INSERT, UPDATE and DELETE operation on the Person table. 
--For that, log all operations performed on the person table into PersonLog.
CREATE TRIGGER TR_PERSON_LOG
ON PERSON
FOR INSERT, UPDATE, DELETE
AS 
BEGIN
	DECLARE @PERSONID INT;
	DECLARE	@PERSONNAME VARCHAR(250);
	DECLARE @OPERATION VARCHAR(50);
	DECLARE @UPDATEDATE DATETIME=GETDATE();

	IF EXISTS(SELECT * FROM INSERTED)
	BEGIN
		SELECT @PERSONID=PERSONID,@PERSONNAME=PERSONNAME FROM INSERTED;
		SET @OPERATION='INSERT';
		INSERT INTO PersonLog VALUES(@PERSONID,@PERSONNAME,@OPERATION,@UPDATEDATE);
	END;

	IF EXISTS(SELECT * FROM DELETED)
	BEGIN
		SELECT @PERSONID=PERSONID,@PERSONNAME=PERSONNAME FROM DELETED;
		SET @OPERATION='DELETE'
		INSERT INTO PersonLog VALUES(@PERSONID,@PERSONNAME,@OPERATION,@UPDATEDATE);
	END;

	IF EXISTS(SELECT * FROM INSERTED) AND EXISTS(SELECT * FROM DELETED)
	BEGIN
		SELECT @PERSONID=PERSONID,@PERSONNAME=PERSONNAME FROM INSERTED;
		SET @OPERATION='UPDATE'
		INSERT INTO PersonLog VALUES(@PERSONID,@PERSONNAME,@OPERATION,@UPDATEDATE);
	END;
END;
SELECT * FROM Person
SELECT * FROM PersonLog

INSERT INTO Person VALUES (3, 'YASH', 77000.00, '2024-01-15', 'DELHI', 30, '1994-05-22');
UPDATE PERSON SET Salary=100000.00 WHERE PersonID=2;

